[package]
name = "cqf-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
bincode = "2.0.0-rc.3"
bitintr = "0.3.0"
itertools = "0.11.0"
rand = "0.8.5"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }

[profile.release]
lto = true
codegen-units = 1
