[package]
name = "cqf-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bitintr = "0.3.0"
bitvec = "1.0.1"
indicatif = "0.17.5"
rand = "0.8.5"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }
